#ifndef DOS_INTERFACE_H
#define DOS_INTERFACE_H

typedef struct DOSBase * pDOSBase;

#if 1

#define SplitName(a, b, c, d, e)	_LIBCALL(DOSBase,  5, INT32, (pDOSBase, STRPTR, INT32, STRPTR, INT32, INT32), (DOSBase,a, b, c, d, e))
#define FilePart(a)					_LIBCALL(DOSBase,  6, STRPTR, (pDOSBase, CONST_STRPTR), (DOSBase,a))
#define PathPart(a)					_LIBCALL(DOSBase,  7, STRPTR, (pDOSBase, CONST_STRPTR), (DOSBase,a))
#define AddPart(a,b,c)				_LIBCALL(DOSBase,  8, DOSIO, (pDOSBase, STRPTR, STRPTR, UINT32), (DOSBase,a,b,c))
#define SendPkt(a,b,c)				_LIBCALL(DOSBase,  9, DOSCALL, (pDOSBase, pDosPacket, pMsgPort, pMsgPort), (DOSBase,a,b,c))
#define ReplyPkt(a,b,c)				_LIBCALL(DOSBase, 10, DOSCALL, (pDOSBase, pDosPacket, INT32, INT32), (DOSBase,a,b,c))
#define AbortPkt(a,b)				_LIBCALL(DOSBase, 11, DOSCALL, (pDOSBase, pDosPacket, pMsgPort), (DOSBase,a,b))
#define WaitPkt()					_LIBCALL(DOSBase, 12, pDosPacket, (pDOSBase), (DOSBase))
#define DoPkt(a,b,c,d,e,f,g)		_LIBCALL(DOSBase, 13, DOSIO, (pDOSBase, pMsgPort, INT32,INT32,INT32,INT32,INT32,INT32), (DOSBase,a,b,c,d,e,f,g))
#define CreatePkt()					_LIBCALL(DOSBase, 14, pDosPacket, (pDOSBase), (DOSBase))
#define DeletePkt(a)				_LIBCALL(DOSBase, 15, DOSCMD, (pDOSBase, pDosPacket), (DOSBase,a))
#define IoErr()						_LIBCALL(DOSBase, 16, DOSCALL, (pDOSBase), (DOSBase))
#define SetIoErr(a)					_LIBCALL(DOSBase, 17, DOSCALL, (pDOSBase, INT32), (DOSBase,a))
#define CheckSignal(a)				_LIBCALL(DOSBase, 18, INT32, (pDOSBase, INT32), (DOSBase,a))
#define FindProcess(a)				_LIBCALL(DOSBase, 19, pProcess, (pDOSBase, STRPTR), (DOSBase,a))
#define CreateProcess(a)			_LIBCALL(DOSBase, 20, pProcess, (pDOSBase, pTagItem), (DOSBase,a))
#define CreateProcessTags(x...)		_LIBCALL(DOSBase, 21, pProcess, (pDOSBase, Tag,...), (DOSBase,##x))
#define AddDosEntry(a)				_LIBCALL(DOSBase, 25, DOSCALL, (pDOSBase, pDosEntry), (DOSBase,a))
#define RemDosEntry(a)				_LIBCALL(DOSBase, 26, DOSCALL, (pDOSBase, pDosEntry), (DOSBase,a))
#define MakeDosEntry(a,b)			_LIBCALL(DOSBase, 27, pDosEntry, (pDOSBase, STRPTR, INT32), (DOSBase,a,b))
#define FreeDosEntry(a)				_LIBCALL(DOSBase, 28, DOSCALL, (pDOSBase, pDosEntry), (DOSBase,a))
#define FindDosEntry(a,b,c)			_LIBCALL(DOSBase, 29, pDosEntry, (pDOSBase, pDosEntry, STRPTR, UINT32), (DOSBase,a,b,c))
#define NextDosEntry(a,b)			_LIBCALL(DOSBase, 30, pDosEntry , (pDOSBase, pDosEntry, UINT32), (DOSBase,a,b))
#define LockDosList(a)				_LIBCALL(DOSBase, 31, DOSCALL, (pDOSBase, UINT32), (DOSBase,a))
#define AttemptLockDosList(a)		_LIBCALL(DOSBase, 32, DOSCALL, (pDOSBase, UINT32), (DOSBase,a))
#define UnLockDosList(a)			_LIBCALL(DOSBase, 33, DOSCALL, (pDOSBase, UINT32), (DOSBase,a))
#define ObtainHandler(a)			_LIBCALL(DOSBase, 34, pHandlerProc, (pDOSBase, STRPTR), (DOSBase,a))
#define ReleaseHandler(a)			_LIBCALL(DOSBase, 35, DOSCALL, (pDOSBase, pHandlerProc), (DOSBase,a))
#define Lock(a, b)					_LIBCALL(DOSBase, 36, pFileLock , (pDOSBase, STRPTR, INT32), (DOSBase,a, b))
#define UnLock(a)					_LIBCALL(DOSBase, 37, DOSIO, (pDOSBase, pFileLock), (DOSBase,a))
#define SetComment(a,b)				_LIBCALL(DOSBase, 38, DOSIO, (pDOSBase, STRPTR, STRPTR), (DOSBase,a,b))
#define CreateDir(a)				_LIBCALL(DOSBase, 39, pFileLock , (pDOSBase, STRPTR), (DOSBase,a))
#define DeleteFile(a)				_LIBCALL(DOSBase, 40, DOSIO, (pDOSBase, STRPTR), (DOSBase,a))
#define SetFileDate(a,b)			_LIBCALL(DOSBase, 41, DOSIO, (pDOSBase, STRPTR, struct DateStamp *), (DOSBase,a,b))
#define SetOwner(a,b)				_LIBCALL(DOSBase, 42, DOSIO, (pDOSBase, STRPTR, INT32), (DOSBase,a,b))
#define SetProtection(a,b)			_LIBCALL(DOSBase, 43, DOSIO, (pDOSBase, STRPTR, INT32), (DOSBase,a,b))
#define ReadLink(a,b,c,d,e)			_LIBCALL(DOSBase, 44, DOSIO, (pDOSBase, pMsgPort, pFileLock, UINT8*, UINT8*, UINT32), (DOSBase,a,b,c,d,e))
#define MakeLink(a,b,c)				_LIBCALL(DOSBase, 45, DOSIO, (pDOSBase, STRPTR, INT32, INT32), (DOSBase,a,b,c))
#define SetConsoleTask(a)			_LIBCALL(DOSBase, 46, pMsgPort, (pDOSBase, pMsgPort), (DOSBase,a))
#define GetConsoleTask()			_LIBCALL(DOSBase, 47, pMsgPort, (pDOSBase), (DOSBase))
#define CurrentDir(a)				_LIBCALL(DOSBase, 48, pFileLock, (pDOSBase, pFileLock), (DOSBase,a))
#define GetCurrentDirName(a,b)		_LIBCALL(DOSBase, 49, DOSIO, (pDOSBase, STRPTR, INT32), (DOSBase,a,b))
#define SetFileSystemTask(a)		_LIBCALL(DOSBase, 50, pMsgPort, (pDOSBase, pMsgPort), (DOSBase,a))
#define GetFileSystemTask()			_LIBCALL(DOSBase, 51, pMsgPort, (pDOSBase), (DOSBase))
#define SetProgramDir(a)			_LIBCALL(DOSBase, 52, pFileLock, (pDOSBase, pFileLock), (DOSBase,a))
#define GetProgramDir()				_LIBCALL(DOSBase, 53, pFileLock, (pDOSBase), (DOSBase))
#define Cli()						_LIBCALL(DOSBase, 54, pComLinInt, (pDOSBase), (DOSBase))
#define Output()					_LIBCALL(DOSBase, 55, pFileHandle, (pDOSBase), (DOSBase))
#define SelectOutput(a)				_LIBCALL(DOSBase, 56, pFileHandle, (pDOSBase,pFileHandle), (DOSBase,a))
#define Input()						_LIBCALL(DOSBase, 57, pFileHandle, (pDOSBase), (DOSBase))
#define SelectInput(a)				_LIBCALL(DOSBase, 58, pFileHandle, (pDOSBase,pFileHandle), (DOSBase,a))
#define SetArgStr(a)				_LIBCALL(DOSBase, 59, STRPTR, (pDOSBase,STRPTR), (DOSBase,a))
#define GetArgStr()					_LIBCALL(DOSBase, 60, STRPTR, (pDOSBase), (DOSBase))
#define Open(a,b)					_LIBCALL(DOSBase, 61, pFileHandle, (pDOSBase,STRPTR, INT32), (DOSBase,a,b))
#define Close(a)					_LIBCALL(DOSBase, 62, DOSIO, (pDOSBase, pFileHandle), (DOSBase,a))
#define Write(a,b,c)				_LIBCALL(DOSBase, 63, DOSIO, (pDOSBase, pFileHandle, UINT8*, INT32), (DOSBase,a,b,c))
#define Read(a,b,c)					_LIBCALL(DOSBase, 64, DOSIO, (pDOSBase, pFileHandle, UINT8*, INT32), (DOSBase,a,b,c))
#define Seek(a,b,c)					_LIBCALL(DOSBase, 65, DOSIO, (pDOSBase, pFileHandle, INT32, INT32), (DOSBase,a,b,c))
#define SetFileSize(a,b,c)			_LIBCALL(DOSBase, 66, DOSIO, (pDOSBase, pFileHandle, INT32, INT32), (DOSBase,a,b,c))
#define DupLockFromFH(a)			_LIBCALL(DOSBase, 67, pFileLock	 , (pDOSBase, pFileHandle), (DOSBase,a))
#define ParentOfFH(a)				_LIBCALL(DOSBase, 68, pFileLock	 , (pDOSBase, pFileHandle), (DOSBase,a))
#define UnLockRecord(a,b,c)			_LIBCALL(DOSBase, 69, DOSIO, (pDOSBase, pFileHandle, INT32, INT32), (DOSBase,a,b,c))
#define LockRecord(a,b,c,d,e)		_LIBCALL(DOSBase, 70, DOSIO, (pDOSBase, pFileHandle, INT32, INT32,INT32,INT32), (DOSBase,a,b,c,d,e))
#define WaitForChar(a,b)			_LIBCALL(DOSBase, 71, DOSIO, (pDOSBase, pFileHandle, INT32), (DOSBase,a,b))
#define VFPrintf(a,b,c)				_LIBCALL(DOSBase, 72, DOSIO, (pDOSBase, pFileHandle, CONST_STRPTR, INT32 *), (DOSBase,a,b,c))
#define VPrintf(a,b)				_LIBCALL(DOSBase, 73, DOSIO, (pDOSBase, CONST_STRPTR, INT32 *), (DOSBase,a,b))
#define VFWritef(a,b,c)				_LIBCALL(DOSBase, 74, DOSIO, (pDOSBase, pFileHandle, CONST_STRPTR, INT32 *), (DOSBase,a,b,c))
#define GetPrompt(a,b)				_LIBCALL(DOSBase, 75, DOSIO, (pDOSBase, STRPTR, INT32), (DOSBase,a,b))
#define DateStamp(a)				_LIBCALL(DOSBase, 76, void, (pDOSBase, pDateStamp), (DOSBase,a))
#define CLI_Init(a)					_LIBCALL(DOSBase, 77, DOSIO, (pDOSBase, pDosPacket), (DOSBase,a))
#define CliInit(a)					_LIBCALL(DOSBase, 78, DOSIO, (pDOSBase, pDosPacket), (DOSBase,a))
#define CLI_Init3(a)				_LIBCALL(DOSBase, 79, DOSIO, (pDOSBase, pDosPacket), (DOSBase,a))
#define Examine(a,b)				_LIBCALL(DOSBase, 80, DOSIO, (pDOSBase, pFileLock, struct FileInfoBlock *), (DOSBase,a,b))
#define ExNext(a,b)					_LIBCALL(DOSBase, 81, DOSIO, (pDOSBase, pFileLock, struct FileInfoBlock *), (DOSBase,a,b))
#define ExamineFH(a,b)				_LIBCALL(DOSBase, 82, DOSIO, (pDOSBase, pFileHandle, struct FileInfoBlock *), (DOSBase,a,b))
#define Info(a,b)					_LIBCALL(DOSBase, 83, DOSIO, (pDOSBase, pFileLock, struct FileInfoBlock *), (DOSBase,a,b))
#define ParentDir(a)				_LIBCALL(DOSBase, 84, pFileLock, (pDOSBase, pFileLock), (DOSBase,a))
#define DupLock(a)					_LIBCALL(DOSBase, 85, pFileLock, (pDOSBase, pFileLock), (DOSBase,a))
#define OpenFromLock(a)				_LIBCALL(DOSBase, 86, pFileHandle, (pDOSBase, pFileLock), (DOSBase,a))
#define SetVar(a,b,c,d)				_LIBCALL(DOSBase, 87, INT32, (pDOSBase, CONST_STRPTR , UINT8*, INT32, UINT32), (DOSBase,a,b,c,d))
#define GetVar(a,b,c,d)				_LIBCALL(DOSBase, 88, INT32, (pDOSBase, CONST_STRPTR , UINT8*, INT32, UINT32), (DOSBase,a,b,c,d))
#define FindVar(a,b)				_LIBCALL(DOSBase, 89, pLocalVar, (pDOSBase, CONST_STRPTR ,UINT32), (DOSBase,a,b))
#define DeleteVar(a,b)				_LIBCALL(DOSBase, 90, INT32, (pDOSBase, CONST_STRPTR ,UINT32), (DOSBase,a,b))
#define FPutC(a,b)					_LIBCALL(DOSBase, 91, DOSIO, (pDOSBase, pFileHandle, INT32), (DOSBase,a,b))
#define FPuts(a,b)					_LIBCALL(DOSBase, 92, DOSIO, (pDOSBase, pFileHandle, STRPTR), (DOSBase,a,b))
#define FRead(a,b,c,d)				_LIBCALL(DOSBase, 93, DOSIO, (pDOSBase, pFileHandle, APTR, UINT32, UINT32), (DOSBase,a,b,c,d))
#define FGetC(a)					_LIBCALL(DOSBase, 94, DOSIO, (pDOSBase, pFileHandle), (DOSBase,a))
#define FGets(a,b,c)				_LIBCALL(DOSBase, 95, STRPTR, (pDOSBase, pFileHandle, STRPTR, UINT32), (DOSBase,a,b,c))
#define FWrite(a,b,c,d)				_LIBCALL(DOSBase, 96, DOSIO, (pDOSBase, pFileHandle, APTR, UINT32, UINT32), (DOSBase,a,b,c,d))
#define Flush(a)					_LIBCALL(DOSBase, 97, DOSIO, (pDOSBase, pFileHandle), (DOSBase,a))
#define ReadArgs(a,b)				_LIBCALL(DOSBase, 98, pRDargs	 , (pDOSBase,  STRPTR, UINT32*), (DOSBase,a,b))
#define FreeArgs(a)					_LIBCALL(DOSBase, 99, void	, (pDOSBase, pRDargs), (DOSBase,a))
#define Fault(a,b,c,d)				_LIBCALL(DOSBase, 100, DOSIO, (pDOSBase, INT32, CONST_STRPTR, STRPTR, INT32), (DOSBase,a,b,c,d))
#define PrintFault(a,b)				_LIBCALL(DOSBase, 101, DOSIO, (pDOSBase, INT32, STRPTR), (DOSBase,a,b))
#define AddSegment(a,b,c)			_LIBCALL(DOSBase, 102, DOSCALL, (pDOSBase, STRPTR, pSegment, INT32), (DOSBase,a,b,c))
#define RemSegment(a)				_LIBCALL(DOSBase, 103, DOSCALL, (pDOSBase, pSegment), (DOSBase,a))
#define FindSegment(a,b,c)			_LIBCALL(DOSBase, 104, pSegment, (pDOSBase, STRPTR, pSegment, BOOL), (DOSBase,a,b,c))
#define RunCommand(a,b,c,d)			_LIBCALL(DOSBase, 105, DOSCALL, (pDOSBase, pSegment, INT32, UINT8*, INT32), (DOSBase,a,b,c,d))
#define LockSegList()				_LIBCALL(DOSBase, 106, DOSCALL, (pDOSBase), (DOSBase))
#define UnLockSegList()				_LIBCALL(DOSBase, 107, DOSCALL, (pDOSBase), (DOSBase))
#define LockSegment(a)				_LIBCALL(DOSBase, 108, DOSCALL, (pDOSBase, pSegment), (DOSBase,a))
#define UnLockSegment(a)			_LIBCALL(DOSBase, 109, DOSCALL, (pDOSBase, pSegment), (DOSBase,a))
#define SetPrompt(a)				_LIBCALL(DOSBase, 110, DOSIO, (pDOSBase, STRPTR), (DOSBase,a))
#define SetProgramName(a)			_LIBCALL(DOSBase, 111, DOSIO, (pDOSBase, STRPTR), (DOSBase,a))
#define UnGetC(a,b)					_LIBCALL(DOSBase, 112, DOSIO, (pDOSBase, pFileHandle, INT32), (DOSBase,a,b))
#define WriteChars(a,b)				_LIBCALL(DOSBase, 113, DOSIO, (pDOSBase, STRPTR, INT32), (DOSBase,a,b))
#define PutStr(a)					_LIBCALL(DOSBase, 114, DOSIO, (pDOSBase, STRPTR), (DOSBase,a))
#define SetCurrentDirName(a)		_LIBCALL(DOSBase, 115, DOSIO, (pDOSBase, STRPTR), (DOSBase,a))
#define NameFromLock(a,b,c)			_LIBCALL(DOSBase, 116, DOSIO, (pDOSBase, pFileLock, STRPTR, INT32), (DOSBase,a,b,c))
#define MatchPattern(a,b)			_LIBCALL(DOSBase, 117, DOSIO, (pDOSBase, CONST_STRPTR, CONST_STRPTR), (DOSBase,a,b))
#define MatchPatternNoCase(a,b)		_LIBCALL(DOSBase, 118, DOSIO, (pDOSBase, CONST_STRPTR, CONST_STRPTR), (DOSBase,a,b))
#define ParsePattern(a,b,c)			_LIBCALL(DOSBase, 119, DOSIO, (pDOSBase, CONST_STRPTR, STRPTR, INT32), (DOSBase,a,b,c))
#define ParsePatternNoCase(a,b,c)	_LIBCALL(DOSBase, 120, DOSIO, (pDOSBase, CONST_STRPTR, STRPTR, INT32), (DOSBase,a,b,c))
#define MatchFirst(a,b)				_LIBCALL(DOSBase, 121, DOSIO, (pDOSBase, STRPTR, struct AnchorPath *), (DOSBase,a,b))
#define MatchEnd(a)					_LIBCALL(DOSBase, 122, DOSIO, (pDOSBase, struct AnchorPath *), (DOSBase,a))
#define MatchNext(a)				_LIBCALL(DOSBase, 123, DOSIO, (pDOSBase, struct AnchorPath *), (DOSBase,a))
#define SameLock(a,b)				_LIBCALL(DOSBase, 124, DOSIO, (pDOSBase, pFileLock, pFileLock), (DOSBase,a,b))
#define Printf(a...)				_LIBCALL(DOSBase, 125, DOSIO, (pDOSBase, CONST_STRPTR,...), (DOSBase,##a))
#define Delay(a)					_LIBCALL(DOSBase, 126, void,  (pDOSBase, UINT32), (DOSBase,a))
#define LoadSegment(a)				_LIBCALL(DOSBase, 127, pSegment, (pDOSBase, STRPTR), (DOSBase,a))
#define AddBuffers(a,b)				_LIBCALL(DOSBase, 128, DOSIO, (pDOSBase, STRPTR, INT32), (DOSBase,a,b))
#define Inhibit(a,b)				_LIBCALL(DOSBase, 129, DOSIO, (pDOSBase, STRPTR, INT32), (DOSBase,a,b))
#define UnloadSegment(a)			_LIBCALL(DOSBase, 130, DOSCALL, (pDOSBase, pSegment), (DOSBase,a))
#define AssignLock(a,b)				_LIBCALL(DOSBase, 131, DOSCALL, (pDOSBase, const STRPTR, pFileLock), (DOSBase,a,b))
#define AssignPath(a,b)				_LIBCALL(DOSBase, 132, DOSCALL, (pDOSBase, const STRPTR, STRPTR), (DOSBase,a,b))
#define AssignLate(a,b)				_LIBCALL(DOSBase, 133, DOSCALL, (pDOSBase, const STRPTR, STRPTR), (DOSBase,a,b))
#define AssignAdd(a,b)				_LIBCALL(DOSBase, 134, DOSCALL, (pDOSBase, STRPTR, pFileLock), (DOSBase,a,b))
#define AssignRem(a,b)				_LIBCALL(DOSBase, 135, DOSCALL, (pDOSBase, STRPTR, pFileLock), (DOSBase,a,b))
#define Execute(a,b,c)				_LIBCALL(DOSBase, 136, DOSCALL, (pDOSBase, STRPTR, pFileHandle, pFileHandle), (DOSBase,a,b,c))
#define System(a,b)					_LIBCALL(DOSBase, 137, DOSCALL, (pDOSBase, STRPTR, pTagItem), (DOSBase,a,b))
#define ReadItem(a,b,c)				_LIBCALL(DOSBase, 138, DOSCALL, (pDOSBase, STRPTR, INT32, APTR), (DOSBase,a,b,c))
#define GetString(a)				_LIBCALL(DOSBase, 139, STRPTR,  (pDOSBase, INT32), (DOSBase,a))

#define Rename(a,b)					_LIBCALL(DOSBase, 140, DOSIO,  (pDOSBase, STRPTR, STRPTR), (DOSBase,a,b))
#define IsFileSystem(a)				_LIBCALL(DOSBase, 141, DOSIO,  (pDOSBase, STRPTR), (DOSBase,a))
#define IsInteractive(a)			_LIBCALL(DOSBase, 142, DOSIO,  (pDOSBase, pFileHandle), (DOSBase,a))
#define SameDevice(a,b)				_LIBCALL(DOSBase, 143, DOSIO,  (pDOSBase, pFileLock, pFileLock), (DOSBase,a,b))
#define TimeStamp()					_LIBCALL(DOSBase, 144, DOSIO,  (pDOSBase), (DOSBase))
#define Tell(a)						_LIBCALL(DOSBase, 145, DOSIO,  (pDOSBase, pFileHandle), (DOSBase, a))

#else

#define SplitName(a, b, c, d, e)	(((INT32	 (*)(pDOSBase, STRPTR, INT32, STRPTR, INT32, INT32))			_GETVECADDR(DOSBase, 5))(DOSBase,a,b,c,d,e))
#define FilePart(a)					(((STRPTR	 (*)(pDOSBase, CONST_STRPTR))									_GETVECADDR(DOSBase, 6))(DOSBase,a))
#define PathPart(a)					(((STRPTR	 (*)(pDOSBase, CONST_STRPTR))									_GETVECADDR(DOSBase, 7))(DOSBase,a))
#define AddPart(a,b,c)				(((DOSIO	 (*)(pDOSBase, STRPTR, STRPTR, UINT32))							_GETVECADDR(DOSBase, 8))(DOSBase,a,b,c))

#define SendPkt(a,b,c)				(((DOSCALL	 (*)(pDOSBase, pDosPacket, pMsgPort, pMsgPort))					_GETVECADDR(DOSBase, 9))(DOSBase,a,b,c))
#define ReplyPkt(a,b,c)				(((DOSCALL	 (*)(pDOSBase, pDosPacket, INT32, INT32))						_GETVECADDR(DOSBase,10))(DOSBase,a,b,c))
#define AbortPkt(a,b)				(((DOSCALL	 (*)(pDOSBase, pDosPacket, pMsgPort))							_GETVECADDR(DOSBase,11))(DOSBase,a,b))
#define WaitPkt()					(((pDosPacket(*)(pDOSBase))													_GETVECADDR(DOSBase,12))(DOSBase))
#define DoPkt(a,b,c,d,e,f,g)		(((DOSIO	 (*)(pDOSBase, pMsgPort, INT32,INT32,INT32,INT32,INT32,INT32))	_GETVECADDR(DOSBase,13))(DOSBase,a,b,c,d,e,f,g))
#define CreatePkt()					(((pDosPacket(*)(pDOSBase))													_GETVECADDR(DOSBase,14))(DOSBase))
#define DeletePkt(a)				(((DOSCMD	 (*)(pDOSBase, pDosPacket))										_GETVECADDR(DOSBase,15))(DOSBase,a))

#define IoErr()						(((DOSCALL	 (*)(pDOSBase))													_GETVECADDR(DOSBase,16))(DOSBase))
#define SetIoErr(a)					(((DOSCALL	 (*)(pDOSBase, INT32))											_GETVECADDR(DOSBase,17))(DOSBase,a))

#define CheckSignal(a)				(((INT32	 (*)(pDOSBase, INT32))											_GETVECADDR(DOSBase,18))(DOSBase, a))
#define FindProcess(a)				(((pProcess	 (*)(pDOSBase, STRPTR))											_GETVECADDR(DOSBase,19))(DOSBase, a))

#define CreateProcess(a)			(((pProcess	 (*)(pDOSBase, pTagItem))										_GETVECADDR(DOSBase,20))(DOSBase, a))
#define CreateProcessTags(x...)		(((pProcess	 (*)(pDOSBase, Tag,...))										_GETVECADDR(DOSBase,21))(DOSBase, ##x))

// leave space 3 for Process, start with 25

#define AddDosEntry(a)				(((DOSCALL	 (*)(pDOSBase, pDosEntry))										_GETVECADDR(DOSBase,25))(DOSBase,a))
#define RemDosEntry(a)				(((DOSCALL	 (*)(pDOSBase, pDosEntry))										_GETVECADDR(DOSBase,26))(DOSBase,a))
#define MakeDosEntry(a,b)			(((pDosEntry (*)(pDOSBase, STRPTR, INT32))									_GETVECADDR(DOSBase,27))(DOSBase,a,b))
#define FreeDosEntry(a)				(((DOSCALL	 (*)(pDOSBase, pDosEntry))										_GETVECADDR(DOSBase,28))(DOSBase,a))
#define FindDosEntry(a,b,c)			(((pDosEntry (*)(pDOSBase, pDosEntry, STRPTR, UINT32))						_GETVECADDR(DOSBase,29))(DOSBase,a,b,c))
#define NextDosEntry(a,b)			(((pDosEntry (*)(pDOSBase, pDosEntry, UINT32))								_GETVECADDR(DOSBase,30))(DOSBase,a,b))

#define LockDosList(a)				(((DOSCALL	 (*)(pDOSBase, UINT32))											_GETVECADDR(DOSBase,31))(DOSBase,a))
#define AttemptLockDosList(a)		(((DOSCALL	 (*)(pDOSBase, UINT32))											_GETVECADDR(DOSBase,32))(DOSBase,a))
#define UnLockDosList(a)			(((DOSCALL	 (*)(pDOSBase, UINT32))											_GETVECADDR(DOSBase,33))(DOSBase,a))

#define ObtainHandler(a)			(((pHandlerProc	 (*)(pDOSBase, STRPTR))										_GETVECADDR(DOSBase,34))(DOSBase,a))
#define ReleaseHandler(a)			(((DOSCALL	 (*)(pDOSBase, pHandlerProc))									_GETVECADDR(DOSBase,35))(DOSBase,a))


#define Lock(a, b)					(((pFileLock (*)(pDOSBase, STRPTR, INT32))									_GETVECADDR(DOSBase,36))(DOSBase,a,b))
#define UnLock(a)					(((DOSIO	 (*)(pDOSBase, pFileLock))										_GETVECADDR(DOSBase,37))(DOSBase,a))

#define SetComment(a,b)				(((DOSIO	 (*)(pDOSBase, STRPTR, STRPTR))									_GETVECADDR(DOSBase,38))(DOSBase,a,b))
#define CreateDir(a)				(((pFileLock (*)(pDOSBase, STRPTR))											_GETVECADDR(DOSBase,39))(DOSBase,a))
#define DeleteFile(a)				(((DOSIO	 (*)(pDOSBase, STRPTR))											_GETVECADDR(DOSBase,40))(DOSBase,a))

#define SetFileDate(a,b)			(((DOSIO	 (*)(pDOSBase, STRPTR, struct DateStamp *))						_GETVECADDR(DOSBase,41))(DOSBase,a,b))
#define SetOwner(a,b)				(((DOSIO	 (*)(pDOSBase, STRPTR, INT32))									_GETVECADDR(DOSBase,42))(DOSBase,a,b))
#define SetProtection(a,b)			(((DOSIO	 (*)(pDOSBase, STRPTR, INT32))									_GETVECADDR(DOSBase,43))(DOSBase,a,b))
#define ReadLink(a,b,c,d,e)			(((DOSIO	 (*)(pDOSBase, pMsgPort, pFileLock, UINT8*, UINT8*, UINT32))	_GETVECADDR(DOSBase,44))(DOSBase,a,b,c,d,e))
#define MakeLink(a,b,c)				(((DOSIO	 (*)(pDOSBase, STRPTR, INT32, INT32))							_GETVECADDR(DOSBase,45))(DOSBase,a,b,c))

#define SetConsoleTask(a)			(((pMsgPort	 (*)(pDOSBase, pMsgPort))										_GETVECADDR(DOSBase,46))(DOSBase,a))
#define GetConsoleTask()			(((pMsgPort	 (*)(pDOSBase))													_GETVECADDR(DOSBase,47))(DOSBase))

#define CurrentDir(a)				(((pFileLock (*)(pDOSBase, pFileLock))										_GETVECADDR(DOSBase,48))(DOSBase,a))
#define GetCurrentDirName(a,b)		(((DOSIO	 (*)(pDOSBase, STRPTR, INT32))									_GETVECADDR(DOSBase,49))(DOSBase,a,b))
#define SetFileSystemTask(a)		(((pMsgPort	 (*)(pDOSBase, pMsgPort))										_GETVECADDR(DOSBase,50))(DOSBase,a))
#define GetFileSystemTask()			(((pMsgPort	 (*)(pDOSBase))													_GETVECADDR(DOSBase,51))(DOSBase))
#define SetProgramDir(a)			(((pFileLock (*)(pDOSBase, pFileLock))										_GETVECADDR(DOSBase,52))(DOSBase,a))
#define GetProgramDir()				(((pFileLock (*)(pDOSBase))													_GETVECADDR(DOSBase,53))(DOSBase))
#define Cli()						(((pComLinInt(*)(pDOSBase))													_GETVECADDR(DOSBase,54))(DOSBase))

#define Output()					(((pFileHandle(*)(pDOSBase))												_GETVECADDR(DOSBase,55))(DOSBase))
#define SelectOutput(a)				(((pFileHandle(*)(pDOSBase,pFileHandle))									_GETVECADDR(DOSBase,56))(DOSBase, a))
#define Input()						(((pFileHandle(*)(pDOSBase))												_GETVECADDR(DOSBase,57))(DOSBase))
#define SelectInput(a)				(((pFileHandle(*)(pDOSBase,pFileHandle))									_GETVECADDR(DOSBase,58))(DOSBase, a))
#define SetArgStr(a)				(((STRPTR	 (*)(pDOSBase,STRPTR))											_GETVECADDR(DOSBase,59))(DOSBase, a))
#define GetArgStr()					(((STRPTR	 (*)(pDOSBase))													_GETVECADDR(DOSBase,60))(DOSBase))
#define Open(a,b)					(((pFileHandle(*)(pDOSBase,STRPTR, INT32))									_GETVECADDR(DOSBase,61))(DOSBase, a,b))
#define Close(a)					(((DOSIO	  (*)(pDOSBase, pFileHandle))									_GETVECADDR(DOSBase,62))(DOSBase,a))
#define Write(a,b,c)				(((DOSIO	 (*)(pDOSBase, pFileHandle, UINT8*, INT32))						_GETVECADDR(DOSBase,63))(DOSBase,a,b,c))
#define Read(a,b,c)					(((DOSIO	 (*)(pDOSBase, pFileHandle, UINT8*, INT32))						_GETVECADDR(DOSBase,64))(DOSBase,a,b,c))
#define Seek(a,b,c)					(((DOSIO	 (*)(pDOSBase, pFileHandle, INT32, INT32))						_GETVECADDR(DOSBase,65))(DOSBase,a,b,c))
#define SetFileSize(a,b,c)			(((DOSIO	 (*)(pDOSBase, pFileHandle, INT32, INT32))						_GETVECADDR(DOSBase,66))(DOSBase,a,b,c))
#define DupLockFromFH(a)			(((pFileLock	 (*)(pDOSBase, pFileHandle))								_GETVECADDR(DOSBase,67))(DOSBase,a))
#define ParentOfFH(a)				(((pFileLock	 (*)(pDOSBase, pFileHandle))								_GETVECADDR(DOSBase,68))(DOSBase,a))
#define UnLockRecord(a,b,c)			(((DOSIO	 (*)(pDOSBase, pFileHandle, INT32, INT32))						_GETVECADDR(DOSBase,69))(DOSBase,a,b,c))
#define LockRecord(a,b,c,d,e)		(((DOSIO	 (*)(pDOSBase, pFileHandle, INT32, INT32,INT32,INT32))			_GETVECADDR(DOSBase,70))(DOSBase,a,b,c,d,e))
#define WaitForChar(a,b)			(((DOSIO	 (*)(pDOSBase, pFileHandle, INT32))								_GETVECADDR(DOSBase,71))(DOSBase,a,b))

#define VFPrintf(a,b,c)				(((DOSIO	 (*)(pDOSBase, pFileHandle, CONST_STRPTR, INT32 *))				_GETVECADDR(DOSBase,72))(DOSBase,a,b,c))
#define VPrintf(a,b)				(((DOSIO	 (*)(pDOSBase, CONST_STRPTR, INT32 *))							_GETVECADDR(DOSBase,73))(DOSBase,a,b))
#define VFWritef(a,b,c)				(((DOSIO	 (*)(pDOSBase, pFileHandle, CONST_STRPTR, INT32 *))				_GETVECADDR(DOSBase,74))(DOSBase,a,b,c))
#define GetPrompt(a,b)				(((DOSIO	 (*)(pDOSBase, STRPTR, INT32))									_GETVECADDR(DOSBase,75))(DOSBase,a,b))
#define DateStamp(a)				(((void(*)(pDOSBase, pDateStamp)) 											_GETVECADDR(DOSBase,76))(DOSBase,a))

#define CLI_Init(a)					(((DOSIO	 (*)(pDOSBase, pDosPacket)) 									_GETVECADDR(DOSBase,77))(DOSBase,a))
#define CliInit(a)					(((DOSIO	 (*)(pDOSBase, pDosPacket)) 									_GETVECADDR(DOSBase,78))(DOSBase,a))
#define CLI_Init3(a)				(((DOSIO	 (*)(pDOSBase, pDosPacket)) 									_GETVECADDR(DOSBase,79))(DOSBase,a))

#define Examine(a,b)				(((DOSIO	 (*)(pDOSBase, pFileLock, struct FileInfoBlock *))  			_GETVECADDR(DOSBase,80))(DOSBase,a,b))
#define ExNext(a,b)					(((DOSIO	 (*)(pDOSBase, pFileLock, struct FileInfoBlock *))  			_GETVECADDR(DOSBase,81))(DOSBase,a,b))
#define ExamineFH(a,b)				(((DOSIO	 (*)(pDOSBase, pFileHandle, struct FileInfoBlock *))  			_GETVECADDR(DOSBase,82))(DOSBase,a,b))
#define Info(a,b)					(((DOSIO	 (*)(pDOSBase, pFileLock, struct FileInfoBlock *))  			_GETVECADDR(DOSBase,83))(DOSBase,a,b))

#define ParentDir(a)				(((pFileLock(*)(pDOSBase, pFileLock))  										_GETVECADDR(DOSBase,84))(DOSBase,a))
#define DupLock(a)					(((pFileLock(*)(pDOSBase, pFileLock))										_GETVECADDR(DOSBase,85))(DOSBase,a))
#define OpenFromLock(a)				(((pFileHandle(*)(pDOSBase, pFileLock))										_GETVECADDR(DOSBase,86))(DOSBase,a))

#define SetVar(a,b,c,d)				(((INT32	(*)(pDOSBase, CONST_STRPTR , UINT8*, INT32, UINT32))			_GETVECADDR(DOSBase,87))(DOSBase,a,b,c,d))
#define GetVar(a,b,c,d)				(((INT32	(*)(pDOSBase, CONST_STRPTR , UINT8*, INT32, UINT32))			_GETVECADDR(DOSBase,88))(DOSBase,a,b,c,d))
#define FindVar(a,b)				(((pLocalVar(*)(pDOSBase, CONST_STRPTR ,UINT32))							_GETVECADDR(DOSBase,89))(DOSBase,a,b))
#define DeleteVar(a,b)				(((INT32	(*)(pDOSBase, CONST_STRPTR ,UINT32))							_GETVECADDR(DOSBase,90))(DOSBase,a,b))

#define FPutC(a,b)					(((DOSIO	 (*)(pDOSBase, pFileHandle, INT32))								_GETVECADDR(DOSBase,91))(DOSBase,a,b))
#define FPuts(a,b)					(((DOSIO	 (*)(pDOSBase, pFileHandle, STRPTR))							_GETVECADDR(DOSBase,92))(DOSBase,a,b))
#define FRead(a,b,c,d)				(((DOSIO	 (*)(pDOSBase, pFileHandle, APTR, UINT32, UINT32))				_GETVECADDR(DOSBase,93))(DOSBase,a,b,c,d))
#define FGetC(a)					(((DOSIO	 (*)(pDOSBase, pFileHandle))									_GETVECADDR(DOSBase,94))(DOSBase,a))
#define FGets(a,b,c)				(((STRPTR	 (*)(pDOSBase, pFileHandle, STRPTR, UINT32))					_GETVECADDR(DOSBase,95))(DOSBase,a,b,c))
#define FWrite(a,b,c,d)				(((DOSIO	 (*)(pDOSBase, pFileHandle, APTR, UINT32, UINT32))				_GETVECADDR(DOSBase,96))(DOSBase,a,b,c,d))
#define Flush(a)					(((DOSIO	 (*)(pDOSBase, pFileHandle))									_GETVECADDR(DOSBase,97))(DOSBase,a))

#define	ReadArgs(a,b)				(((pRDargs	 (*)(pDOSBase,  STRPTR, UINT32*))								_GETVECADDR(DOSBase,98))(DOSBase,a,b))
#define FreeArgs(a)					(((void		 (*)(pDOSBase, pRDargs))										_GETVECADDR(DOSBase,99))(DOSBase,a))

#define Fault(a,b,c,d)				(((DOSIO	 (*)(pDOSBase, INT32, CONST_STRPTR, STRPTR, INT32))				_GETVECADDR(DOSBase,100))(DOSBase,a,b,c,d))
#define PrintFault(a,b)				(((DOSIO	 (*)(pDOSBase, INT32, STRPTR))									_GETVECADDR(DOSBase,101))(DOSBase,a,b))

#define AddSegment(a,b,c)			(((DOSCALL	 (*)(pDOSBase, STRPTR, pSegment, INT32))						_GETVECADDR(DOSBase,102))(DOSBase,a,b,c))
#define RemSegment(a)				(((DOSCALL	 (*)(pDOSBase, pSegment))										_GETVECADDR(DOSBase,103))(DOSBase,a))
#define FindSegment(a,b,c)			(((pSegment	 (*)(pDOSBase, STRPTR, pSegment, BOOL))							_GETVECADDR(DOSBase,104))(DOSBase,a,b,c))
#define RunCommand(a,b,c,d)			(((DOSCALL	 (*)(pDOSBase, pSegment, INT32, UINT8*, INT32))					_GETVECADDR(DOSBase,105))(DOSBase,a,b,c,d))

#define LockSegList()				(((DOSCALL	 (*)(pDOSBase))													_GETVECADDR(DOSBase,106))(DOSBase))
#define UnLockSegList()				(((DOSCALL	 (*)(pDOSBase))													_GETVECADDR(DOSBase,107))(DOSBase))
#define LockSegment(a)				(((DOSCALL	 (*)(pDOSBase, pSegment))										_GETVECADDR(DOSBase,108))(DOSBase,a))
#define UnLockSegment(a)			(((DOSCALL	 (*)(pDOSBase, pSegment))										_GETVECADDR(DOSBase,109))(DOSBase,a))

#define SetPrompt(a)				(((DOSIO	 (*)(pDOSBase, STRPTR))											_GETVECADDR(DOSBase,110))(DOSBase,a))
#define SetProgramName(a)			(((DOSIO	 (*)(pDOSBase, STRPTR))											_GETVECADDR(DOSBase,111))(DOSBase,a))

#define UnGetC(a,b)					(((DOSIO	 (*)(pDOSBase, pFileHandle, INT32))								_GETVECADDR(DOSBase,112))(DOSBase,a,b))
#define WriteChars(a,b)				(((DOSIO	 (*)(pDOSBase, STRPTR, INT32))									_GETVECADDR(DOSBase,113))(DOSBase,a,b))
#define PutStr(a)					(((DOSIO	 (*)(pDOSBase, STRPTR))											_GETVECADDR(DOSBase,114))(DOSBase,a))

#define SetCurrentDirName(a)		(((DOSIO	 (*)(pDOSBase, STRPTR))											_GETVECADDR(DOSBase,115))(DOSBase,a))
#define NameFromLock(a,b,c)			(((DOSIO	 (*)(pDOSBase, pFileLock, STRPTR, INT32))						_GETVECADDR(DOSBase,116))(DOSBase,a,b,c))

#define MatchPattern(a,b)			(((DOSIO	 (*)(pDOSBase, CONST_STRPTR, CONST_STRPTR))						_GETVECADDR(DOSBase,117))(DOSBase,a,b))
#define MatchPatternNoCase(a,b)		(((DOSIO	 (*)(pDOSBase, CONST_STRPTR, CONST_STRPTR))						_GETVECADDR(DOSBase,118))(DOSBase,a,b))
#define ParsePattern(a,b,c)			(((DOSIO	 (*)(pDOSBase, CONST_STRPTR, STRPTR, INT32))					_GETVECADDR(DOSBase,119))(DOSBase,a,b,c))
#define ParsePatternNoCase(a,b,c)	(((DOSIO	 (*)(pDOSBase, CONST_STRPTR, STRPTR, INT32))					_GETVECADDR(DOSBase,120))(DOSBase,a,b,c))

#define MatchFirst(a,b)				(((DOSIO	 (*)(pDOSBase, STRPTR, struct AnchorPath *))					_GETVECADDR(DOSBase,121))(DOSBase,a,b))
#define MatchEnd(a)					(((DOSIO	 (*)(pDOSBase, struct AnchorPath *))							_GETVECADDR(DOSBase,122))(DOSBase,a))
#define MatchNext(a)				(((DOSIO	 (*)(pDOSBase, struct AnchorPath *))							_GETVECADDR(DOSBase,123))(DOSBase,a))

#define SameLock(a,b)				(((DOSIO	 (*)(pDOSBase, pFileLock, pFileLock))							_GETVECADDR(DOSBase,124))(DOSBase,a,b))

#define Printf(a...)				(((DOSIO	 (*)(pDOSBase, CONST_STRPTR,...))								_GETVECADDR(DOSBase,125))(DOSBase,##a))
#define Delay(a)					(((void		 (*)(pDOSBase, UINT32))											_GETVECADDR(DOSBase,126))(DOSBase,a))

#define LoadSegment(a)				(((pSegment		 (*)(pDOSBase, STRPTR))										_GETVECADDR(DOSBase,127))(DOSBase,a))
#define AddBuffers(a,b)				(((DOSIO	 (*)(pDOSBase, STRPTR, INT32))									_GETVECADDR(DOSBase,128))(DOSBase,a,b))
#define Inhibit(a,b)				(((DOSIO	 (*)(pDOSBase, STRPTR, INT32))									_GETVECADDR(DOSBase,129))(DOSBase,a,b))
#define UnloadSegment(a)			(((DOSCALL	 (*)(pDOSBase, pSegment))										_GETVECADDR(DOSBase,130))(DOSBase,a))

#define AssignLock(a,b)				(((DOSCALL	 (*)(pDOSBase, const STRPTR, pFileLock))						_GETVECADDR(DOSBase,131))(DOSBase,a,b))
#define AssignPath(a,b)				(((DOSCALL	 (*)(pDOSBase, const STRPTR, STRPTR))							_GETVECADDR(DOSBase,132))(DOSBase,a,b))
#define AssignLate(a,b)				(((DOSCALL	 (*)(pDOSBase, const STRPTR, STRPTR))							_GETVECADDR(DOSBase,133))(DOSBase,a,b))
#define AssignAdd(a,b)				(((DOSCALL	 (*)(pDOSBase, STRPTR, pFileLock))								_GETVECADDR(DOSBase,134))(DOSBase,a,b))
#define AssignRem(a,b)				(((DOSCALL	 (*)(pDOSBase, STRPTR, pFileLock))								_GETVECADDR(DOSBase,135))(DOSBase,a,b))

#define Execute(a,b,c)				(((DOSCALL	 (*)(pDOSBase, STRPTR, pFileHandle, pFileHandle))				_GETVECADDR(DOSBase,136))(DOSBase,a,b,c))
#define System(a,b)					(((DOSCALL	 (*)(pDOSBase, STRPTR, pTagItem))								_GETVECADDR(DOSBase,137))(DOSBase,a,b))
	
#define ReadItem(a,b,c)				(((DOSCALL	 (*)(pDOSBase, STRPTR, INT32, APTR))							_GETVECADDR(DOSBase,138))(DOSBase,a,b,c))
#define GetString(a)				(((STRPTR	 (*)(pDOSBase, INT32))											_GETVECADDR(DOSBase,139))(DOSBase,a))

#endif
	
//Dummy
#define ErrorReport(a,b,c,d)		(((BOOL(*)(pDOSBase, INT32, INT32, UINT32, pMsgPort)) 						_GETVECADDR(DOSBase,23))(DOSBase,a,b,c,d))
//#define NameFromLock(a,b,c)			(((DOSIO(*)(pDOSBase, pFileLock, UINT8 *, UINT32)) _GETVECADDR(DOSBase,23))(DOSBase,a,b,c))
//#define MatchPatternNoCase(a,b)		(((BOOL(*)(pDOSBase, STRPTR, STRPTR)) _GETVECADDR(DOSBase,23))(DOSBase,a,b))


#endif
