#ifndef DOS_ERROR_H
#define DOS_ERROR_H

// Standard error codes for PowerDOS
#define ERROR_NO_FREE_STORE				103
#define ERROR_TASK_TABLE_FULL			105
#define ERROR_BAD_TEMPLATE				114
#define ERROR_BAD_NUMBER				115
#define ERROR_REQUIRED_ARG_MISSING		116
#define ERROR_KEY_NEEDS_ARG				117
#define ERROR_TOO_MANY_ARGS				118
#define ERROR_UNMATCHED_QUOTES			119
#define ERROR_LINE_TOO_LONG				120
#define ERROR_FILE_NOT_OBJECT			121
#define ERROR_INVALID_RESIDENT_LIBRARY	122
#define ERROR_BAD_ARGUMENTS				123
#define ERROR_COMMAND_LONG 				124
#define ERROR_NO_DEFAULT_DIR			201
#define ERROR_OBJECT_IN_USE				202
#define ERROR_OBJECT_EXISTS				203
#define ERROR_DIR_NOT_FOUND				204
#define ERROR_OBJECT_NOT_FOUND			205
#define ERROR_BAD_STREAM_NAME			206
#define ERROR_OBJECT_TOO_LARGE			207
#define ERROR_ACTION_NOT_KNOWN			209
#define ERROR_INVALID_COMPONENT_NAME	210
#define ERROR_INVALID_LOCK				211
#define ERROR_OBJECT_WRONG_TYPE			212
#define ERROR_DISK_NOT_VALIDATED		213
#define ERROR_DISK_WRITE_PROTECTED		214
#define ERROR_RENAME_ACROSS_DEVICES		215
#define ERROR_DIRECTORY_NOT_EMPTY		216
#define ERROR_TOO_MANY_LEVELS			217
#define ERROR_DEVICE_NOT_MOUNTED		218
#define ERROR_SEEK_ERROR				219
#define ERROR_COMMENT_TOO_BIG			220	
#define ERROR_DISK_FULL					221
#define ERROR_DELETE_PROTECTED			222
#define ERROR_WRITE_PROTECTED			223 
#define ERROR_READ_PROTECTED			224
#define ERROR_NOT_A_DOS_DISK			225
#define ERROR_NO_DISK					226
#define ERROR_NO_MORE_ENTRIES			232
#define ERROR_IS_SOFT_LINK				233
#define ERROR_OBJECT_LINKED				234
#define ERROR_BAD_HUNK					235
#define ERROR_NOT_IMPLEMENTED			236
#define ERROR_RECORD_NOT_LOCKED			240
#define ERROR_LOCK_COLLISION			241
#define ERROR_LOCK_TIMEOUT				242
#define ERROR_UNLOCK_ERROR				243

#define ERROR_DISK_CORRUPTED      244
#define ERROR_IO_FAILURE          245
#define ERROR_FILENAME_TOO_LONG   246
#define ERROR_ILLEGAL_FILENAME    247
#define ERROR_NON_UNIQUE_FILENAME 248

#define ERROR_NO_PACKET					500
#define ERROR_ASYNC_PACKET				501
#define ERROR_NO_PROCESS				502
#define ERROR_SYSTEMCALL				600

// STRING ERROR CODES:
#define STR_VOLUME		-100
#define STR_IS_NOT_VALIDATED	-101
#define STR_IS_WRITE_PROTECTED	-102
#define STR_IS_FULL		-103
#define STR_PLEASE_INSERT	-104
#define STR_PLEASE_REPLACE	-105
#define STR_IN_ANY_DRIVE	-106
#define STR_NOT_A_DOS_DISK	-107
#define STR_NO_DISK_PRESENT	-108
#define STR_HAS_RW_ERROR	-109
#define STR_MUST_REPLACE	-110
#define STR_IN_UNIT		-111
#define STR_IN_DEVICE		-112
#define STR_WAIT_DISK		-113
#define STR_TASK_FAILED		-114
#define STR_DISK_CORRUPT	-115
#define STR_UNUSED		-116
#define STR_ERROR		-117

#define STR_REDIRECTION		-118
#define STR_SYNTAX_ERROR	-119
#define STR_UNABLE_TO_LOAD	-120
#define STR_UNKNOWN_COMMAND	-121
#define STR_ERROR_COMMAND	-122
#define STR_SHELL_ERROR		-123
#define STR_COMMAND_TOO_LONG	-124
#define STR_TOO_MANY_REDIR	-125
#define STR_RETRY_CANCEL	-126
#define STR_REBOOT_SUSPEND	-127
#define STR_CANT_OPEN_FROM	-128
#define STR_NEW_CLI_PROCESS	-129
#define STR_CANT_CREATE_PROC	-130

#define STR_CANT_SET            -141
#define STR_TOO_MANY_MATCHES    -142
#define STR_NOT_EXECUTE         -143
#define STR_MISSING_ELSE        -144
#define STR_NEWSHELL_FAILED     -145
#define STR_CURRENT_STACK       -146
#define STR_STACK_LARGE         -147
#define STR_STACK_SMALL         -148
#define STR_PROCESS_ENDING      -149
#define STR_LAST_MSG_FAILED     -150
#define STR_NO_RETURN_CODE      -151
#define STR_CURRENT_DIR         -152
#define STR_BAD_RETURN_CODE     -153
#define STR_FAIL_LIMIT          -154
#define STR_FAULT               -155
#define STR_TH_SYSTEM           -156
#define STR_TH_INTERNAL         -157
#define STR_TH_DISABLED         -158
#define STR_NAME                -159
#define STR_TH_USE_COUNT        -160

#define STR_FAILED_RETURNCODE	-161
#define STR_SOFTWARE_FAILURE	-162

#define ABORT_DISK_ERROR	296	/* Read/write error */
#define ABORT_BUSY		288	/* You MUST replace... */

#define ERROR_BUFFER_OVERFLOW	303	/* User or internal buffer overflow */
#define ERROR_BREAK		304	/* A break character was received */
#define ERROR_NOT_EXECUTABLE	305	/* A file has E bit cleared */
#endif
